[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "upyt"
version = "0.0.1"
dependencies = [
    "pyserial",
]

[project.scripts]
upyt-terminal = "upyt.cli.terminal:main"
